server:
  port: 8080

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    distribution.percentiles-histogram.http:
      server.requests: true
      client.requests: true
    export:
      prometheus:
        enabled: true
