server:
  port: 8090

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres/userdb
    username: postgres
    password: postgres

kafka:
  configuration:
    bootstrap-servers:
      - broker-1:9091
      - broker-2:9091
    topic-name: email-notification
    partitions: 2
    srUrl: schema-registry

scheduler:
  delay: 5000
