server:
  port: 8090

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres/userdb
    username: postgres
    password: postgres

kafka:
  configuration:
    bootstrap-servers:
      - broker-1:19092
      - broker-2:19092
    topic-name: email-notification
    partitions: 2
    srUrl: schema-registry

scheduler:
  delay: 5000
